import 'package:freezed_annotation/freezed_annotation.dart';

part 'blossom_models.freezed.dart';
part 'blossom_models.g.dart';

/// Status of a blob upload operation.
///
/// Upload flow: pending -> uploading -> processing -> completed
/// On error: any state -> failed
enum UploadStatus {
  /// Upload has not started yet
  pending,

  /// File is being uploaded to the server
  uploading,

  /// Server is processing the uploaded file
  processing,

  /// Upload completed successfully
  completed,

  /// Upload failed with an error
  failed,
}

/// Metadata for a blob stored on a Blossom server.
///
/// Blossom uses content-addressed storage where each blob is
/// identified by its SHA-256 hash. This model represents the
/// metadata returned by the server after upload or when listing blobs.
///
/// Example:
/// ```dart
/// final blob = BlossomBlob(
///   sha256: 'abc123...',
///   size: 1024000,
///   mimeType: 'image/jpeg',
///   uploadedAt: DateTime.now(),
///   url: 'https://blossom.primal.net/abc123...',
/// );
/// ```
@freezed
class BlossomBlob with _$BlossomBlob {
  const factory BlossomBlob({
    /// SHA-256 hash of the blob content (hex encoded)
    required String sha256,

    /// Size of the blob in bytes
    required int size,

    /// MIME type of the blob (e.g., 'image/jpeg')
    required String mimeType,

    /// When the blob was uploaded to the server
    required DateTime uploadedAt,

    /// Full URL to access the blob
    required String url,

    /// Original filename (if provided during upload)
    String? fileName,

    /// Blurhash for image previews (if generated by server)
    String? blurhash,

    /// Image dimensions (if applicable)
    int? width,
    int? height,
  }) = _BlossomBlob;

  factory BlossomBlob.fromJson(Map<String, dynamic> json) =>
      _$BlossomBlobFromJson(json);

  /// Creates a BlossomBlob from Blossom server response.
  ///
  /// Server responses typically include:
  /// - sha256: hash of the content
  /// - size: file size in bytes
  /// - type: MIME type
  /// - uploaded: Unix timestamp
  /// - url: full URL to access the blob
  factory BlossomBlob.fromServerResponse(
    Map<String, dynamic> response,
    String serverUrl,
  ) {
    final sha256 = response['sha256'] as String? ?? response['hash'] as String;
    final uploaded = response['uploaded'] as int? ?? response['created'] as int?;

    return BlossomBlob(
      sha256: sha256,
      size: response['size'] as int? ?? 0,
      mimeType: response['type'] as String? ?? 'application/octet-stream',
      uploadedAt: uploaded != null
          ? DateTime.fromMillisecondsSinceEpoch(uploaded * 1000)
          : DateTime.now(),
      url: response['url'] as String? ?? '$serverUrl/$sha256',
      fileName: response['name'] as String?,
      blurhash: response['blurhash'] as String?,
      width: response['width'] as int?,
      height: response['height'] as int?,
    );
  }
}

/// Progress information for an ongoing upload.
///
/// Emitted by [BlossomService.uploadFile] to track upload progress.
/// The progress percentage can be calculated as:
/// `(bytesUploaded / totalBytes) * 100`
///
/// Example:
/// ```dart
/// blossomService.uploadProgress.listen((progress) {
///   print('${progress.fileName}: ${progress.percentage}%');
///   if (progress.status == UploadStatus.completed) {
///     print('URL: ${progress.blobUrl}');
///   }
/// });
/// ```
@freezed
class UploadProgress with _$UploadProgress {
  const factory UploadProgress({
    /// Original filename being uploaded
    required String fileName,

    /// Bytes uploaded so far
    required int bytesUploaded,

    /// Total file size in bytes
    required int totalBytes,

    /// Current upload status
    required UploadStatus status,

    /// SHA-256 hash of the file (available after hashing)
    String? sha256,

    /// Error message if upload failed
    String? error,

    /// Resulting blob URL (available after completion)
    String? blobUrl,

    /// Server URL the file was uploaded to
    String? serverUrl,
  }) = _UploadProgress;

  /// Private constructor for custom getters
  const UploadProgress._();

  factory UploadProgress.fromJson(Map<String, dynamic> json) =>
      _$UploadProgressFromJson(json);

  /// Initial progress state for a new upload.
  factory UploadProgress.initial(String fileName, int totalBytes) =>
      UploadProgress(
        fileName: fileName,
        bytesUploaded: 0,
        totalBytes: totalBytes,
        status: UploadStatus.pending,
      );

  /// Progress percentage (0-100).
  double get percentage {
    if (totalBytes == 0) return 0;
    return (bytesUploaded / totalBytes) * 100;
  }

  /// Whether the upload is still in progress.
  bool get isInProgress =>
      status == UploadStatus.uploading || status == UploadStatus.processing;

  /// Whether the upload has finished (completed or failed).
  bool get isFinished =>
      status == UploadStatus.completed || status == UploadStatus.failed;
}

/// Result of a Blossom operation.
///
/// Generic result type for Blossom operations that can either
/// succeed with a value or fail with an error message.
@freezed
class BlossomResult<T> with _$BlossomResult<T> {
  /// Successful operation with result data.
  const factory BlossomResult.success(T data) = BlossomSuccess<T>;

  /// Failed operation with error message.
  const factory BlossomResult.failure(String error) = BlossomFailure<T>;

  /// Private constructor for pattern matching helpers
  const BlossomResult._();

  /// Whether the operation succeeded.
  bool get isSuccess => this is BlossomSuccess<T>;

  /// Whether the operation failed.
  bool get isFailure => this is BlossomFailure<T>;

  /// Get the data if successful, null otherwise.
  T? get dataOrNull {
    final result = this;
    if (result is BlossomSuccess<T>) {
      return result.data;
    }
    return null;
  }

  /// Get the error message if failed, null otherwise.
  String? get errorOrNull {
    final result = this;
    if (result is BlossomFailure<T>) {
      return result.error;
    }
    return null;
  }
}
